# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CoreDataFun' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5'
platform :ios, '6.1'
pod 'SDWebImage', '~>3.7'

end

